version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/test-for-ec2

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  BeforeInstall:
    - location: scripts/before.sh
      runas: root
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root